### PR TITLE
Fix NSID decoding error

### PR DESCRIPTION
**Pull request by fcelda**
I'm submitting a patch which fixes NSID parsing in the current version of DNSViz and dnspython.

Current error:

```
% ./bin/dnsviz grok -r /tmp/probe.json
Traceback (most recent call last):
  File "/home/jan/devel/dnsviz/./bin/dnsviz", line 141, in <module>
    main()
  File "/home/jan/devel/dnsviz/./bin/dnsviz", line 138, in main
    mod.main(args)
  File "/home/jan/devel/dnsviz/dnsviz/commands/grok.py", line 491, in main
    name_obj.serialize_status(d, loglevel=arghelper.log_level)
  File "/home/jan/devel/dnsviz/dnsviz/analysis/offline.py", line 3310, in serialize_status
    query_serialized = self._serialize_query_status(self.queries[(qname, rdtype)], consolidate_clients=consolidate_clients, loglevel=loglevel, html_format=html_format)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jan/devel/dnsviz/dnsviz/analysis/offline.py", line 3067, in _serialize_query_status
    rrset_serialized = self._serialize_rrset_info(rrset_info, consolidate_clients=consolidate_clients, loglevel=loglevel, html_format=html_format)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jan/devel/dnsviz/dnsviz/analysis/offline.py", line 2874, in _serialize_rrset_info
    rrsig_serialized = rrsig_status.serialize(consolidate_clients=consolidate_clients, loglevel=loglevel, html_format=html_format, map_ip_to_ns_name=self.zone.get_ns_name_for_ip)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jan/devel/dnsviz/dnsviz/analysis/status.py", line 385, in serialize
    nsid = response.nsid_val()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jan/devel/dnsviz/dnsviz/response.py", line 225, in nsid_val
    nsid_val = nsid_opt.data.decode('ascii')
               ^^^^^^^^^^^^^
AttributeError: 'NSIDOption' object has no attribute 'data'
```

### CODE REVIEW

**Comment by cdeccio** [comment]
Hi @fcelda , thanks for the PR!  I didn't even know that dnspython had changed their code.  This is backwards incompatible with earlier versions, so to make it compatible, I would like something like this at the beginning:

```
        # Compatibility with both dnspython 1.6 and earlier versions.
        # dnspython introduced the NSIDOption type, which has an nsid member,
        # whereas earlier versions use the GenericOption type, which has only a
        # data member.
        if hasattr(nsid_opt, 'nsid'):
            # dnspython >= 2.6 with NSIDOption
            data = nsid_opt.nsid
        else:
            # dnspython < 2.6 with GenericOption
            data = nsid_opt.data
```

Alternatively, the condition could check the type of 
```
        if isinstance(nsid_opt, dns.edns.GenericOption):
            # dnspython < 2.6 with GenericOption
            data = nsid_opt.data
        else:
            # dnspython >= 2.6 with NSIDOption
            data = nsid_opt.nsid
```
(I think I slightly prefer this version.).  I've done just some initial testing, and it seems to work as expected.

In either use `data` instead of `nsid_opt.nsid` later in the code.

Finally, I like the change check only for visible ASCII (which matches the `dns.edns.NSIDOption.to_text()` code), but I have a slight preference to break up that and the rest of the changes into two commits, so it's two that two things are being introduced.

**Comment by cdeccio** [comment]
If it's easier for you that I just accept the PR and make the changes myself, I could do that.

**Comment by fcelda** [comment]
Hey @cdeccio. Thank you for the feedback and also for the patience. This is still on my radar. :slightly_smiling_face: 

Do you think it's worth keeping the backward compatibility with the older dnspython? I wonder whether that is useful or just maintenance burden.

Splitting the two changes into commits makes sense. I will do that. Two commits in a single PR is OK or do you want two separate PRs?

**Comment by cdeccio** [comment]
> Hey @cdeccio. Thank you for the feedback and also for the patience. This is still on my radar. 🙂
> 
> Do you think it's worth keeping the backward compatibility with the older dnspython? I wonder whether that is useful or just maintenance burden.

For now, yes 🙂   Not everyone has version 2.6 yet.  For example, debian stable currently has 2.3.0.  At some point, I'll remove support for older dnspython and (gasp) python 2.7.

> 
> Splitting the two changes into commits makes sense. I will do that. Two commits in a single PR is OK or do you want two separate PRs?

A single PR with two commits is just fine, thanks!  Could you also re-base, now that I've pushed a bunch of changes to the upstream?

**Comment by fcelda** [comment]
There is one more variant of the compatibility handling:

```py
        if hasattr(dns.edns, 'NSIDOption'):
            # dnspython >= 2.6 with NSIDOption
            data = nsid_opt.nsid
        else:
            # dnspython < 2.6 with Generic Option
            data = nsid_opt.data
```

I ended up commiting this variant but can switch to the implementation with `isinstance(nsid_opt, dns.edns.GenericOption)` that you proposed if you think it's cleaner.

I split the changes to two commits and I also added unit test for the NSID parsing.

Please, let me know what you think, @cdeccio.

**Comment by cdeccio** [comment]
> I ended up commiting this variant but can switch to the implementation with `isinstance(nsid_opt, dns.edns.GenericOption)` that you proposed if you think it's cleaner.

I like yours better! 🙂 Thanks!

> I split the changes to two commits and I also added unit test for the NSID parsing.

Perfect!  Thanks for the unit test!  Of course, it reminds me that I need to add many more of those... 😬

**Pull request merged**
