### PR TITLE
Add detection for iteration counts that are considered to high in draft-ietf-dnsop-nsec3-guidance

### PR DESCRIPTION
**Pull request by RobinGeuze**
This adds a warning when the maximum encountered iteration count for NSEC3 is higher than 100, which will be considered insecure once draft-ietf-dnsop-nsec3-guidance gets accepted. Currently many resolvers already consider iteration counts over 150 insecure.

### CODE REVIEW

**Comment by RobinGeuze** [comment]
@cdeccio do we want to put this on hold till the RFC has passed? Or do we preventatively want to put it in since some of the resolvers/recursors are already enforcing a limit?

**Comment by cdeccio** [comment]
@RobinGeuze sorry that I'm just now getting back to this.  I never responded to your question earlier, but my answer is "yes" that I would like to wait for the RFC to be published😄. RFC 9276 changes things quite bit from what they were.  So now the error should be something like NSEC3IterationCountNonZero or something.  Also, we'll need to update the wording on the warning, the references, and anything else that should be updasted.  Most other warnings/errors in DNSViz simply say something like "is disallowed" or "is prohibited" and then reference the RFC (though admittedly the RFC isn't actually displayed anywhere yet--see #92).

**Comment by RobinGeuze** [comment]
Hey @cdeccio, I'll see if I can fix up the PR somewhere next week.

**Comment by RobinGeuze** [comment]
@cdeccio I've updated the PR to reflect the final RFC.

**Comment by cdeccio** [comment]
Thanks @RobinGeuze .  Could you please run `git rebase -i upstream/master` to 1) squash all the commits into a single commit; 2) base the new single commit on the latest upstream commits?  Then force push it to this branch.  Then I'll bring in the pull request.  I might tweak the wording afterwords for consistency.  Thanks!

**Comment by RobinGeuze** [comment]
Squashing and rebasing done.

**Comment by cdeccio** [comment]
Thanks!

**Pull request merged**
