### PR TITLE
Support algo 15 (ed25519) validation

### PR DESCRIPTION
**Pull request by pieterlexis**
This fixes the first part of #28

### CODE REVIEW

**Comment by cdeccio** [comment]
Thanks @pieterlexis !  I'll take a look soon.

**Comment by derekargueta** [comment]
@cdeccio ping on this :)

**Comment by cdeccio** [comment]
Believe it or not, I'm working through this :)  I was waiting for a while to see if M2Crypto and OpenSSL might catch up with edwards curves, so I didn't need another dependency, but I don't think it's problematic to address this immediately and then refactor down the line, if necessary.

That being said, I'm evaluating the code and am working some changes to integrate the functionality, using the code from this PR as a base.  There are some other considerations, including libsodium code versions, that I'm working through.  @pieterlexis thanks for taking the time to put together the code and create the PR.

**Comment by cdeccio** [comment]
Implemented in fd2e63794a85d89120a4c51283e36d6c3516b634, using this PR as a model.  Thanks, @pieterlexis

**Comment by mnordhoff** [comment]
With emphasis that this is just a question and not nagging, do you have an ETA for Ed25519 on http://dnsviz.net/?

**Comment by cdeccio** [comment]
It is a great question :)  The request is in, and hopefully it will happen tomorrow.

Thanks for your patience...

**Comment by mnordhoff** [comment]
Great! :smile: But if it's not tomorrow that's fine too.

**Comment by elyscape** [comment]
Just checking in on this, as it appears to have not yet hit dnsviz.net. Thanks for your work on this!

**Comment by cdeccio** [comment]
Thanks for the ping... This was started, but we ran into some system difficulties along the way, which meant putting it off for a time, so we could deal with those fires.  We're going to try again next week.

**Comment by Darkspirit** [comment]
> We're going to try again next week.

What are the current challenges to deploy that and could it be switched to https (either via Nginx/Apache with Let's Encrypt or by using Cloudflare)?
https://dnsviz.net/d/ed25519.nl/dnssec/

**Pull request closed without merging**
