### PR TITLE
Skip tests when resolv.conf is not available

### PR DESCRIPTION
**Pull request by pemensik**
Another changes to work with pytest better. Return special exit code 5 when resolvers are not available. Check it and skip some tests instead of failing them. Would help in restricted environment builds.

Allow also DNSVIZ_SHARE_PATH override from environment. Needed for testing build, when not yet installed by root into final destination.

### CODE REVIEW

**Comment by pemensik** [comment]
I used it on Fedora package, but it seems such change might hang after pytest finishes. There might be some threads not terminated. Slightly modified version at [Fedora Pull request](https://src.fedoraproject.org/rpms/dnsviz/pull-request/1)

Do not know how to reproduce it in normal environment. It works fine on my machine during local build.

**Comment by pemensik** [comment]
It seems relevant answer to it might be here: https://stackoverflow.com/questions/19219596/py-test-hangs-after-showing-test-results

**Comment by cdeccio** [comment]
Thanks!  I'll take a look to see what is going on, but I might not get to it today.  Thanks for all your work on this.

**Comment by cdeccio** [comment]
@pemensik Sorry that I've waited so long to get back to this.  Could you rebase this, so it can be merged?

Also, note that I've revamped some of the tests.  `./scripts/populate_zones.sh` needs to be run to create some of the zone data that is actually tested.  The tests still aren't comprehensive, but they definitely add more sanity checks.

**Comment by cdeccio** [comment]
I created a new PR #131, which is basically the same as this one but rebased and with conflicts resolved.

Thanks so much!

**Pull request closed without merging**
